name: Release Middly

on:
  push:
    # Trigger the workflow only when you push a tag that looks like v1.0.0
    tags:
      - 'v*'

# Grant permissions for GoReleaser to upload the release assets to GitHub
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Required by GoReleaser to generate the changelog properly
          fetch-depth: 0 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}